# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 012912755d377b214f05f0602be9928e17695f07bb19bb8900ae66609dc95af8bccb3e2d3c38ecad1a0865a26e3756f13d9cda22d1a108f39076009c9e2d5d72

test:
  secret_key_base: 937c9c3d49d7f0ff0ba53e3af8c390a8b195535af29436e39cfaefda62f8875e2983996729b8ac44221f6afcedd5b76be30c261ada59a6fb51899df07c08cb90

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
